#!/usr/bin/env python

import urlparse
import subprocess

from optparse import OptionParser
from rospkg import RosPack
from os import path
from os.path import expanduser

usage = "usage: %prog [options] svn-url"
parser = OptionParser(usage=usage)

(options, args) = parser.parse_args()

if (len(args) != 1):
	parser.print_usage()
else:
	url = args[0]
	rp = RosPack()
	authors_file = expanduser("~/.tue/installer/targets/amigo-user/scripts/git-authors.txt")

	url = urlparse.urlparse(url)

	if url.scheme not in ['http', 'https']:
		raise Exception('only http or https urls')


	if url.netloc != 'roboticssrv.wtb.tue.nl':
		raise Exception('only the roboticssrv.wtb.tue.nl is supported')


	if not url.path.startswith('/svn/ros/'):
		raise Exception('path must start with /svn/ros/')

	path_parts = url.path.partition('/svn/ros/')

	svn = url._replace(path=path_parts[1]).geturl()
	trunk = path_parts[2]

	bashCommand = 'git svn clone %s --trunk %s --authors-file=%s' % (svn, trunk, authors_file)
	print 'Please execute the following command:\n\n', bashCommand


	#process = subprocess.Popen(bashCommand.split(), stdout=subprocess.PIPE)
	#print process.communicate()[0]
