#!/bin/bash

if [ -z "$TUE_ROS_DISTRO" ]
then
    echo "[tue ros setup] TUE_ROS_DISTRO was not set"
    return
fi

TUE_SYSTEM_DIR=$TUE_ENV_DIR/system
TUE_DEV_DIR=$TUE_ENV_DIR/dev

source $TUE_DEV_DIR/devel/setup.bash
