# GitLab CI configuration to use SSH and docker registry
#
# Prerequisities:
# 1. Generate a password less SSH key on a local machine
# 2. Add the public key as a deploy key to the repository/group
# 3. Add the private key as a variable (e.g. SSH_KEY_PRIVATE) to the repository/group

stages:
  - Environment
  - Package Manager

include:
  - local: 'ci/base.gitlab-ci.yml'
  - local: 'ci/docker-buildx.gitlab-ci.yml'
  - local: 'ci/tue-env.gitlab-ci.yml'
