#!/bin/bash

set -e

function run_test {
    #echo Running $BASH_SOURCE
    #echo PWD is $PWD
    AUTHORINFO=$(git var GIT_AUTHOR_IDENT) || exit 1
    NAME=$(printf '%s\n' "${AUTHORINFO}" | sed -n 's/^\(.*\) <.*$/\1/p')
    EMAIL=$(printf '%s\n' "${AUTHORINFO}" | sed -n 's/^.* <\(.*\)> .*$/\1/p')
    echo
    echo "I'm going to commit with \"$NAME <$EMAIL>\""
    [[ "${NAME}" != "amigo" || "${NAME}" != "sergio" ]] || {
        echo "Please commit with a username, run \"git su <name>\" to swith users"
        exit 1
    }

    # prompt for conformation
    exec < /dev/tty
    read -p "Are you sure? " -n 1 -r
    exec <&-
    echo    # (optional) move to a new line
    if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
        exit 1
    fi
}

case "${1}" in
    --about )
        echo "Check that the current user has set a username"
        ;;
    * )
        run_test
        ;;
esac
