#!/bin/bash

export ROBOT_BRINGUP_PATH=/home/amigo/ros/hydro/system/src/sergio_bringup

alias sergio-core='export ROS_MASTER_URI=http://sergio1:11311'

####################
#
# SSH
#
####################
alias sshsergio1='until ssh -qo ConnectTimeout=1 -X amigo@sergio1; do echo waiting for sergio1 to come online...; sleep 2; done'
alias sshsergio2='until ssh -qo ConnectTimeout=1 -X amigo@sergio2; do echo waiting for sergio2 to come online...; sleep 2; done'
alias sshsergio3='until ssh -qo ConnectTimeout=1 -X amigo@sergio3; do echo waiting for sergio3 to come online...; sleep 2; done'


####################
#
# SERGIO STARTUP
#
####################
alias sstart='roslaunch sergio_bringup start.launch'
alias shardware='roslaunch sergio_bringup hardware.launch'
alias smiddle='roslaunch sergio_bringup middleware.launch'

####################
#
# SERGIO ACTIONS
#
####################
alias sergio-teleop='rosrun tue_teleop_keyboard teleop_twist_keyboard.py /cmd_vel:=/sergio/base/references'
# alias rviz-sergio=''

#####################
#
# DIAGNOSTICS
#
#####################
alias diag='rosrun robot_monitor robot_monitor'
alias sdashboard='tue-dashboard sergio1'

alias rviz-sergio='rosrun rviz rviz -d ~/.tue/installer/targets/sergio-user/rviz_config.rviz'

#####################
#
# SERGIO FUNCTIONS
#
#####################
function sergio-torso-move-spindle {
    if [ -z "$2" ]; then
        echo "Used for testing. Usage: sergio-torso-move-spindle lower_spindle upper_splindl"
        return
    fi

    ( rostopic pub /sergio/torso/references sensor_msgs/JointState "{header: {seq: 0, stamp: {secs: 0, nsecs: 0}, frame_id: ''}, name: ['torso_lower_spindle', 'torso_upper_spindle'], position: [$1, $2], velocity: [0], effort: [0]}"  --once  &> /dev/null & )
}

function sergio-torso-move-joints {
    if [ -z "$2" ]; then
        echo "Usage: sergio-torso-move-joints ankle_joint hip_joint"
        echo "Physical limits: ankle_joint 0.05 to 1.00 [rad]"
        echo "                 hip_joint   1.01 to 2.31 [rad]"
        echo "Note: knee-joint is estimated with use of the ankle_joint. test"
        return
    fi
    
    ( rostopic pub /sergio/torso/references sensor_msgs/JointState "{header: {seq: 0, stamp: {secs: 0, nsecs: 0}, frame_id: ''}, name: ['ankle_joint', 'knee_joint', 'hip_joint'], position: [$1, $(echo "1.874*$1+0.1323" |bc) , $2], velocity: [0], effort: [0]}"  --once  &> /dev/null & )
}

function sergio-torso-laser-move {
    if [ -z "$1" ]; then
        echo "Usage: sergio-torso-laser-move LASER_TILT    (range -0.02~0.29)"
        return
    fi

    rostopic pub /sergio/dynamixel/references sensor_msgs/JointState "{header: {seq: 0, stamp: {secs: 0, nsecs: 0}, frame_id: ''}, name: ['laser_tilt_joint'], position: [$1], velocity: [0], effort: [0]}"  --once
}

function sergio-head-move {
    if [ -z "$2" ]; then
        echo "Usage: sergio-head-move PAN TILT"
        return
    fi

    rostopic pub /sergio/dynamixel/references sensor_msgs/JointState "{header: {seq: 0, stamp: {secs: 0, nsecs: 0}, frame_id: ''}, name: ['neck_pan_joint', 'neck_tilt_joint'], position: [$1, $2], velocity: [0], effort: [0]}"  --once
}
