#!/usr/bin/env python

import os, re

tue_dir = os.getenv('TUE_DIR', '$/.tue')
authorsFile = os.path.join(os.path.expanduser(tue_dir), 'installer/targets/amigo-user/scripts/git-authors.txt')

author_re = re.compile(r'(\w+)\s*=\s*([^<]+?)\s*<([^>]*)>')

with file('gitsu.txt', 'w') as out_f:
	with file(authorsFile) as f:
		for line in f.readlines():
			m = author_re.search(line)
			if not m:
				print 'no match for: "%s"' % line
				continue

			authorNick  = m.group(1)
			authorName  = m.group(2)
			authorEmail = m.group(3)

			print 'parsing %s\t"%s" "%s" "%s"\n' % (line, authorNick, authorName, authorEmail)

			out_f.write('%s : %s\n' % (authorEmail, authorName))
