#! /usr/bin/env bash

function tue-revert
{
    human_time="$*"

    fs=`ls $_TUE_CATKIN_SYSTEM_DIR/src`
    for pkg in $fs
    do
        pkg_dir=$_TUE_CATKIN_SYSTEM_DIR/src/$pkg

        if [ -d $pkg_dir ]
        then
            cd $pkg_dir
            branch=$(git rev-parse --abbrev-ref HEAD 2>&1)
            if [ $? -eq 0 ] && [ $branch != "HEAD" ]
            then
                new_hash=$(git rev-list -1 --before="$human_time" $branch)
                current_hash=$(git rev-parse HEAD)
                git diff -s --exit-code $new_hash $current_hash
                if [ $? -eq 0 ]
                then
                    newtime=$(git show -s --format=%ci)
                    printf "\e[0;36m%-20s\033[0m %-15s \e[1m%s\033[0m %s\n" "$branch is fine" "$new_hash" "$newtime" "$pkg"
                else
                    git checkout -q $new_hash
                    newbranch=$(git rev-parse --abbrev-ref HEAD 2>&1)
                    newtime=$(git show -s --format=%ci)
                    echo $branch > .do_not_commit_this
                    printf "\e[0;36m%-20s\033[0m %-15s \e[1m%s\033[0m %s\n" "$newbranch based on $branch" "$new_hash" "$newtime" "$pkg"
                fi
            else
                echo "Package $pkg could not be reverted, current state: $branch"
            fi
        fi
    done
}

tue-revert $@
