# Setup SSH keys in the environment to allow cloning across all repositories that have enabled
# the deploy key CI_DEPLOY_KEY that is associated with the private key in CI_SSH_KEY_PRIVATE
.ssh_keys: &ssh_keys
  - eval $(ssh-agent -s)
  - |
    cat <<EOT | ssh-add -
    -----BEGIN OPENSSH PRIVATE KEY-----
    ${CI_SSH_KEY_PRIVATE}
    -----END OPENSSH PRIVATE KEY-----
    EOT
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

# Common script to create manifest for multi-arch images
.manifest:
  script:
    - TARGET_IMAGE="${TARGET_IMAGE_BASE_NAME}:${TARGET_IMAGE_TAG}"
    - |
      IMAGES_TO_COMBINE=
      for arch in amd64 arm64; do
        if docker manifest inspect ${TARGET_IMAGE}-${arch}; then
          IMAGES_TO_COMBINE="${IMAGES_TO_COMBINE} ${TARGET_IMAGE}-${arch}"
        fi
      done
      if [[ -z "${IMAGES_TO_COMBINE}" ]]; then
        echo -e "Error! No images to combine!"
        exit 1
      fi
    - docker manifest create ${TARGET_IMAGE} ${IMAGES_TO_COMBINE}
    - docker manifest push ${TARGET_IMAGE}
    - docker manifest inspect --verbose ${TARGET_IMAGE}

# Setups basic pre-conditions for the Docker images build:
# - Installing prerequisites
# - Setup SSH keys
# - Loging into docker registry
.build_image_base:
  image: ${IMAGE_REGISTRY}/docker-buildx:latest

  services:
    - docker:dind

  stage: build

  variables:
    GIT_STRATEGY: clone
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_DRIVER: overlay2
    SHARED_PATH: "/builds/shared/$CI_PROJECT_PATH"
    IMAGE_REGISTRY: "$CI_REGISTRY_IMAGE"

  before_script:
    - apk --update add git bash curl jq openssh-client tree
    - *ssh_keys
    - echo "${CI_JOB_TOKEN}" | docker login ${CI_REGISTRY} -u gitlab-ci-token --password-stdin
    - |
      TARGET_IMAGE_TAG_BRANCH=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:-${CI_COMMIT_BRANCH:-$CI_COMMIT_TAG}}
      if [[ "${TARGET_IMAGE_TAG_BRANCH}" == "${CI_DEFAULT_BRANCH}" ]]; then
          TARGET_IMAGE_TAG="latest"
      else
          TARGET_IMAGE_TAG=$(echo "${TARGET_IMAGE_TAG_BRANCH}" | tr '[:upper:]' '[:lower:]' | sed -e 's:/:_:g')
      fi
