# GitLab CI configuration to use SSH and docker registry
#
# Prerequisities:
# 1. Generate a password less SSH key on a local machine
# 2. Add the public key as a deploy key to the repository/group
#    - Settings > Repository > Deploy keys.
#    Either add the public key here or enable one from "Privately accessible deploy keys"
# 3. Add the private key as a variable (e.g. SSH_KEY_PRIVATE) to the repository/group
# 4. Allow the CI deploy key to have write access if using "Mirror Upstream"
#    - Settings > Repository > Deploy keys > Enabled deploy keys
#    Edit the required key, check "Grant write permissions to this key" and click "Save changes"
#
# 5. Install Build Test Job requires the variable ROS_DISTRO to be set in the CI pipeline.
#    Either set this as a global variable before including this template into a repository
#    or set it as a pipeline variable.

stages:
  - Install Build Test 
  - Mirror Upstream

include:
  - local: 'ci/base.gitlab-ci.yml'
  - local: 'ci/install-build-test.gitlab-ci.yml'
  - local: 'ci/mirror-upstream.gitlab-ci.yml'
