#!/bin/bash

# make sure svn is installed
hash svn 2> /dev/null || sudo apt-get install -y subversion

# Update installer
svn co https://roboticssrv.wtb.tue.nl/svn/ros/tue_env ~/.tue/ --trust-server-cert --non-interactive

# Source the installer commands
source ~/.tue/setup.bash
