#!/bin/bash
set -o errexit # Stop on errors

# make sure git is installed
hash git 2> /dev/null || sudo apt-get install -y git

if [ -e ~/.tue ]
then
	mv -f ~/.tue ~/.tue.$(date +%F_%R)
fi

# Update installer
git clone https://github.com/tue-robotics/tue-env.git ~/.tue

# Create ros environment directory
mkdir -p ~/ros/$TUE_ENV

# Source the installer commands
source ~/.tue/setup.bash
