#!/usr/bin/python

import sys

def main():
    if len(sys.argv) != 2:
        print "Usage: parse-ros-manifest-deps MANIFEST.XML"
        return 1

    import xml.etree.ElementTree as ET

    tree = ET.parse(sys.argv[1])
    doc = tree.getroot()
    deps = doc.findall('depend')

    for dep in deps:
        try:
            print dep.attrib["package"]
        except KeyError:
            pass

if __name__ == "__main__":
    sys.exit(main())
