#!/bin/bash

# Update installer
if [ ! -d ~/.tue ]
then 
    git clone https://github.com/tue-robotics/tue-env.git ~/.tue
else
    mem_pwd=$PWD
    cd ~/.tue
    echo -en "Updating tue-get... "    
    git pull --ff-only --prune
	cd $mem_pwd
fi

# Run installer
source ~/.tue/installer/scripts/tue-install-impl $@
exit $?
