#!/bin/bash
_tue-check-env-vars || exit 1

# Update installer
if [ ! -d $TUE_DIR ]
then 
    git clone https://github.com/tue-robotics/tue-env.git $TUE_DIR
else
    mem_pwd=$PWD
    cd $TUE_DIR
    echo -en "Updating tue-get... "    
    git pull --ff-only --prune

    error_code=$?
	cd $mem_pwd

    if [ ! $error_code -eq 0 ]
    then
        echo ""
        echo "[tue-get] Could not update tue-get. Aborting"
        exit 1
    fi
fi

# Run installer
source $TUE_DIR/installer/scripts/tue-install-impl $@
exit $?
