#!/bin/bash

alias git-logout='git config --global --get user.name > /dev/null && git config --global --remove user'

# If this is run the first since this computer was started, remove
# the user details (forcing the user to 'log-in')
if [ ! -f /tmp/git-removed-user-details ]
then
    touch /tmp/git-removed-user-details
    git-logout
fi

# Set lg alias
if ! git config --global --get alias.lg > /dev/null
then
    git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
fi

# Set push default
if ! git config --global --get push.default > /dev/null
then
    git config --global push.default "current"
fi
