name: Cleanup container tags

on: [delete, push, workflow_dispatch]

jobs:
  delete_container_tag:
    name: Delete container tag
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package_name: ["tue-env-ros-noetic", "tue-env-ros-galactic", "tue-env-ros-humble"]
    steps:
      - name: Generate tag
        id: generate-tag
        run: |
          TAG=$(echo "${{ github.event.ref }}" | tr '[:upper:]' '[:lower:]' | sed -e 's:/:_:g')
          TAG="fix\_cleanup"
          echo "tag=${TAG}\-.*" >> ${GITHUB_OUTPUT}
      - uses: castlabs/get-package-version-id-action@v2.1
        id: version-ids
        with:
          version: ${{ steps.generate-tag.outputs.tag }}
      - uses: actions/delete-package-versions@v4
        if: ${{ steps.version-ids.outputs.ids != '' }}
        with:
          package-name: ${{ matrix.package_name }}
          package-type: container
          package-version-ids: ${{ steps.version-ids.outputs.ids }}
