name: Cleanup container tags

on: delete

jobs:
  delete_container_tag:
    name: Delete container tag
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package_name: ["tue-env-ros-noetic", "tue-env-ros-galactic", "tue-env-ros-humble"]
    steps:
      - name: Generate tag
        id: generate-tag
        run: |
          TAG=$(echo "${{ github.event.ref }}" | tr '[:upper:]' '[:lower:]' | sed -e 's:/:_:g')
          echo "tag=${TAG}-amd64" >> ${GITHUB_OUTPUT}
      - uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ matrix.package_name }}
          package-type: container
          package-version-ids: ${{ steps.generate-tag.outputs.tag
