name: 'TUe CI'
description: 'Install, build and test package in tue-env environment'
inputs:
  image:
    default: 'ghcr.io/tue-robotics/tue-env-ros-noetic'
    description: 'Container Image to be used'
    required: false
    type: string
  package:
    description: 'Package name'
    required: true
    type: string
  ssh-key:
    description: 'SSH key used during install process'
    required: false
    type: string
  ssh-known-hosts:
    description: 'Hosts to be added known_hosts'
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - name: Cache ccache
      uses: actions/cache@v4
      with:
        path: |
          ~/.ccache
        key: ${{ runner.os }}-ccache-${{ github.event.repository.name }}-${{ inputs.package }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache-${{ github.event.repository.name }}-${{ inputs.package }}-
          ${{ runner.os }}-ccache-${{ github.event.repository.name }}-
          ${{ runner.os }}-ccache-

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ github.event.repository.name }}-${{ inputs.package }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ github.event.repository.name }}-${{ inputs.package }}-
          ${{ runner.os }}-pip-${{ github.event.repository.name }}-
          ${{ runner.os }}-pip-

    - name: Install
      id: install
      run: |
        echo "::group::install-package.sh"
        GITHUB_REF=${GITHUB_REF#refs/heads/}
        GITHUB_REF=${GITHUB_REF#refs/tags/}
        BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF}}
        DEFAULT_BRANCH=${{ github.event.repository.default_branch }}
        if [[ "$BRANCH" == "$DEFAULT_BRANCH" ]]
        then
            BRANCH=""
        fi
        PULLREQUEST=${{ github.event.number }}
        PULLREQUEST=${PULLREQUEST:-false}
        SSH_KEY="${{ inputs.ssh-key }}"
        SSH_KNOWN_HOSTS="${{ inputs.ssh-known-hosts }}"
        SSH_ARGS=()
        if [[ -n "${SSH_KEY}" ]]
        then
          SSH_KEY_PATH="${HOME}"/.ssh/ci_ssh_key
          echo -e "\e[35;1mmkdir -p ${HOME}/.ssh\e[0m"
          mkdir -p "${HOME}"/.ssh
          echo "${SSH_KEY}" > "${SSH_KEY_PATH}"
          SSH_ARGS+=("--ssh" "--ssh-key=${SSH_KEY_PATH}")
        fi
        if [[ -n "${SSH_KNOWN_HOSTS}" ]]
        then
          echo -e "\e[35;1mmkdir -p ${HOME}/.ssh\e[0m"
          mkdir -p "${HOME}"/.ssh
          for host in ${SSH_KNOWN_HOSTS}
          do
            echo -e "\e[35;1mssh-keyscan -t rsa -H \"${host}\" 2>&1 | tee -a ${HOME}/.ssh/known_hosts\e[0m"
            ssh-keyscan -t rsa -H "${host}" 2>&1 | tee -a "${HOME}"/.ssh/known_hosts
          done
        fi
        DEBUG_ARGS=()
        DEBUG=${RUNNER_DEBUG:+true}
        DEBUG=${DEBUG:-false}
        if [[ ${DEBUG} == "true" ]]
        then
          DEBUG_ARGS+=("--debug")
        fi
        ${{ github.action_path }}/../install-package.sh \
          --image=${{ inputs.image }} \
          --package=${{ inputs.package }} \
          --branch="${BRANCH}" \
          --commit="${GITHUB_SHA}" \
          --pullrequest="${PULLREQUEST}" \
          "${SSH_ARGS[@]}" \
          "${DEBUG_ARGS[@]}"
        echo "::endgroup::"
      shell: bash

    - name: Build
      id: build
      run: |
        echo "::group::build-package.sh"
        DEBUG_ARGS=()
        DEBUG=${RUNNER_DEBUG:+true}
        DEBUG=${DEBUG:-false}
        if [[ ${DEBUG} == "true" ]]
        then
          DEBUG_ARGS+=("--debug")
        fi
        ${{ github.action_path }}/../build-package.sh \
          --package=${{ inputs.package }} \
          "${DEBUG_ARGS[@]}"
        echo "::endgroup::"
      shell: bash

    - name: Test
      id: test
      run: |
        echo "::group::test-package.sh"
        DEBUG_ARGS=()
        DEBUG=${RUNNER_DEBUG:+true}
        DEBUG=${DEBUG:-false}
        if [[ ${DEBUG} == "true" ]]
        then
          DEBUG_ARGS+=("--debug")
        fi
        ${{ github.action_path }}/../test-package.sh \
          --package=${{ inputs.package }} \
          "${DEBUG_ARGS[@]}"
        echo "::endgroup::"
      shell: bash
